version: '3'
networks: 
  template:
services: 
  template-nginx:
    image: nginx:stable-alpine
    container_name: template-nginx
    ports:
      - "8081:80"
    volumes:
      - ./backend/php/laravel:/var/www/laravel
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - template-php
      - template-postgresql
    networks:
      - template
  template-php:
    build:
      context: .
      dockerfile: ./backend/php/dockerfile
    container_name: template-php
    working_dir: "/var/www/laravel"
    volumes:
      - ./backend/php/laravel:/var/www/laravel
    ports:
      - "9000:9000"
    networks:
      - template
  template-postgresql:
    image: mdillon/postgis:10
    container_name: template-postgresql
    tty: true
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./backend/postgresql:/var/lib/postgresql/data
    networks: 
      - template